#!/usr/bin/env bash

# Copyright (c) 2024-08-01 xulinchun <xulinchun0806@outlook.com>
#
# This file is part of LMD.
#
# LMD is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# LMD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LMD.  If not, see <http://www.gnu.org/licenses/>.
#==============================================================================

PYTHON_CMD="python3"

Primary() {
    conda activate main || PYTHON_CMD="/miniconda/envs/main/bin/python"
    $PYTHON_CMD app/app.py
}

Embedding() {
    conda activate embedding || PYTHON_CMD="/miniconda/envs/embedding/bin/python"
    $PYTHON_CMD app/torch_npu_embedding_app.py

}

Rerank() {
    conda activate rerank || PYTHON_CMD="/miniconda/envs/rerank/bin/python"
    $PYTHON_CMD app/torch_npu_rerank_app.py

}

Ngram() {
    conda activate ngram || PYTHON_CMD="/miniconda/envs/ngram/bin/python"
    $PYTHON_CMD app/ngram_app.py

}


main() {
    echo -e "\e[33m##-*--------# Copyright (c) 2024-08-01 xulinchun <xulinchun0806@outlook.com>        *-##\e[0m"
    echo -e "\e[33m##-*--------#                                                                       *-##\e[0m"
    echo -e "\e[33m##-*--------# This file is part of SupieDT-LMD.                                     *-##\e[0m"

    source /usr/local/Ascend/ascend-toolkit/set_env.sh
    export HCCL_CONNECT_TIMEOUT=7200
    export ASCEND_RT_VISIBLE_DEVICES=${DEVICES_NUMS_IDS}

    case $1 in
    Primary)
        Primary
        ;;
    Embedding)
        Embedding
        ;;
    Rerank)
        Rerank
        ;;
    Ngram)
        Ngram
        ;;
    *)
        echo "Option: {Primary|Embedding|Rerank|Ngram}"
        exit 1
        ;;
    esac
}

main "$@" || exit 1