FROM prom/node-exporter:latest

LABEL maintainer="xulinchun xulinchun0806@outlook.com" \
      org.opencontainers.image.authors="xulinchun xulinchun0806@outlook.com" \
      org.opencontainers.image.base.name="alpine" \
      org.opencontainers.image.created="2024-08-06T00:00:00Z" \
      org.opencontainers.image.description="LMD NODE-EXPORTER" \
      org.opencontainers.image.documentation="" \
      org.opencontainers.image.licenses="GPLv2.1" \
      org.opencontainers.image.ref.name="lmd-node-exporter" \
      org.opencontainers.image.source="" \
      org.opencontainers.image.title="lmd-node-exporter" \
      org.opencontainers.image.vendor="xulinchun" \
      org.opencontainers.image.version="v1.8.2"
